spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    create-schemas: true
    url: ${DATABASE_URL}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

server:
  port: ${PORT:8080}

logging:
  level:
    org.flywaydb: DEBUG

app:
  frontend-url: ${FRONTEND_URL}